//initialize the lists
let artist_list = []
artist_list = generate_artist_list();
let card_list = []

// console.log(card_list);

function generate_new_card() {
    //gets the next card in the list and displays it
    const card_title = document.querySelector(".card_title")
    const card_img = document.querySelector(".card_img")
    const artist_link = document.querySelector(".artist_link")
    const card_set = document.querySelector(".card_set")
    const card_rarity = document.querySelector(".card_rarity")
    const card_types = document.querySelector(".card_types")
    const card_subtypes = document.querySelector(".card_subtypes")
    get_card_data();
    
    // console.log(card_list);
    card_title.innerHTML = card_list[0].name;
    card_img.setAttribute("src", card_list[0].imageUrl);
    artist_link.innerHTML = card_list[0].artist;
    let link_url = get_artist_link(card_list[0].artist);
    artist_link.setAttribute("href", link_url);
    card_set.innerHTML = card_list[0].setName;
    card_rarity.innerHTML = card_list[0].rarity;
    if (card_list[0].types != null) {
        for (i=0; i<card_list[0].types.length; i++) {
            card_types.innerHTML = card_list[0].types[i];
        }
    }
    if (card_list[0].subtypes != null) {
        for (i=0; i<card_list[0].subtypes.length; i++) {
            card_subtypes.innerHTML = card_list[0].subtypes[i];
        }
    }
}

async function get_card_data() {
    let response = await fetch("https://api.magicthegathering.io/v1/cards?random=true&pageSize=1");
    let data = await response.json();
    // console.log(data.cards);
    card_list = data.cards;
    // console.log(card_list);
}

function get_artist_link(artist_name) {
    for (i=0; i<artist_list.length; i++) {
        if (artist_name == artist_list[i].name) {
            return artist_list[i].link
        }
    }
}

function generate_artist_list() {
const artist_template = {
    name: "",
    link: ""
};
let artist_list = [];
artist = Object.create(artist_template);
artist["name"] = "Aaron Miller";
artist["link"] = "https://www.artofmtg.com/artist/aaron-miller/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Adam Paquette";
artist["link"] = "https://www.artofmtg.com/artist/adam-paquette/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Adam Rex";
artist["link"] = "https://www.artofmtg.com/artist/adam-rex/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alan Pollack";
artist["link"] = "https://www.artofmtg.com/artist/alan-pollack/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alan Rabinowitz";
artist["link"] = "https://www.artofmtg.com/artist/alan-rabinowitz/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alayna Danner";
artist["link"] = "https://www.artofmtg.com/artist/alayna-danner/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alejandro Mirabal";
artist["link"] = "https://www.artofmtg.com/artist/alejandro-mirabal/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Aleksi Briclot";
artist["link"] = "https://www.artofmtg.com/artist/aleksi-briclot/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alessandra Pisano";
artist["link"] = "https://www.artofmtg.com/artist/alessandra-pisano/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alexander Mokhov";
artist["link"] = "https://www.artofmtg.com/artist/alexander-mokhov/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alex Brock";
artist["link"] = "https://www.artofmtg.com/artist/alex-brock/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alex Horley-Orlandelli";
artist["link"] = "https://www.artofmtg.com/artist/alex-horley-orlandelli/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alexis Hernandez";
artist["link"] = "https://www.artofmtg.com/artist/alexis-hernandez/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alexis Ziritt";
artist["link"] = "https://www.artofmtg.com/artist/alexis-ziritt/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alex Konstad";
artist["link"] = "https://www.artofmtg.com/artist/alex-konstad/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alex Stone";
artist["link"] = "https://www.artofmtg.com/artist/alex-stone/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Alix Branwyn";
artist["link"] = "https://www.artofmtg.com/artist/alix-branwyn/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Allen Douglas";
artist["link"] = "https://www.artofmtg.com/artist/allen-douglas/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Allen Williams";
artist["link"] = "https://www.artofmtg.com/artist/allen-williams/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Allison Carl";
artist["link"] = "https://www.artofmtg.com/artist/allison-carl/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Amy Weber";
artist["link"] = "https://www.artofmtg.com/artist/amy-weber/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anastasia Ovchinnikova";
artist["link"] = "https://www.artofmtg.com/artist/anastasia-ovchinnikova/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anato Finnstark";
artist["link"] = "https://www.artofmtg.com/artist/anato-finnstark/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andrea De Dominicis";
artist["link"] = "https://www.artofmtg.com/artist/andrea-de-dominicis/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andrea Radeck";
artist["link"] = "https://www.artofmtg.com/artist/andrea-radeck/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andreas Rocha";
artist["link"] = "https://www.artofmtg.com/artist/andreas-rocha/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andrew Huerta";
artist["link"] = "https://www.artofmtg.com/artist/andrew-huerta/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andrew Mar";
artist["link"] = "https://www.artofmtg.com/artist/andrew-mar/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andrew Robinson";
artist["link"] = "https://www.artofmtg.com/artist/andrew-robinson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andrey Kuzinskiy";
artist["link"] = "https://www.artofmtg.com/artist/andrey-kuzinskiy/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Andy Brase";
artist["link"] = "https://www.artofmtg.com/artist/andy-brase/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anna Christenson";
artist["link"] = "https://www.artofmtg.com/artist/anna-christenson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anna Fehr";
artist["link"] = "https://www.artofmtg.com/artist/anna-fehr/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anna Pavleeva";
artist["link"] = "https://www.artofmtg.com/artist/anna-pavleeva/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anna Podedworna";
artist["link"] = "https://www.artofmtg.com/artist/anna-podedworna/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anna Steinbauer";
artist["link"] = "https://www.artofmtg.com/artist/anna-steinbauer/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anthony Francisco";
artist["link"] = "https://www.artofmtg.com/artist/anthony-francisco/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anthony Palumbo";
artist["link"] = "https://www.artofmtg.com/artist/anthony-palumbo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Anthony Waters";
artist["link"] = "https://www.artofmtg.com/artist/anthony-waters/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Antonio José Manzanedo";
artist["link"] = "https://www.artofmtg.com/artist/antonio-jose-manzanedo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Artur Treffner";
artist["link"] = "https://www.artofmtg.com/artist/artur-treffner/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Aurore Folny";
artist["link"] = "https://www.artofmtg.com/artist/aurore-folny/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Austin Hsu";
artist["link"] = "https://www.artofmtg.com/artist/austin-hsu/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bad Flip Productions";
artist["link"] = "https://www.artofmtg.com/artist/bad-flip-productions/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Banishing Light";
artist["link"] = "https://www.artofmtg.com/artist/banishing-light/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bartłomiej Gaweł";
artist["link"] = "https://www.artofmtg.com/artist/bartlomiej-gawel/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bastien Grivet";
artist["link"] = "https://www.artofmtg.com/artist/bastien-grivet/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bastien L. Deharme";
artist["link"] = "https://www.artofmtg.com/artist/bastien-l-deharme/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bayard Wu";
artist["link"] = "https://www.artofmtg.com/artist/bayard-wu/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Benjamin Ee";
artist["link"] = "https://www.artofmtg.com/artist/benjamin-ee/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ben Maier";
artist["link"] = "https://www.artofmtg.com/artist/ben-maier/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ben Wootten";
artist["link"] = "https://www.artofmtg.com/artist/ben-wootten/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Billy Christian";
artist["link"] = "https://www.artofmtg.com/artist/billy-christian/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bradley Williams";
artist["link"] = "https://www.artofmtg.com/artist/bradley-williams/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brad Rigney";
artist["link"] = "https://www.artofmtg.com/artist/brad-rigney/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bram Sels";
artist["link"] = "https://www.artofmtg.com/artist/bram-sels/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brandi Milne";
artist["link"] = "https://www.artofmtg.com/artist/brandi-milne/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brandon Dorman";
artist["link"] = "https://www.artofmtg.com/artist/brandon-dorman/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brandon Kitkouski";
artist["link"] = "https://www.artofmtg.com/artist/brandon-kitkouski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brent Hollowell";
artist["link"] = "https://www.artofmtg.com/artist/brent-hollowell/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brian Durfee";
artist["link"] = "https://www.artofmtg.com/artist/brian-durfee/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brian Snoddy";
artist["link"] = "https://www.artofmtg.com/artist/brian-snoddy/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brian Valeza";
artist["link"] = "https://www.artofmtg.com/artist/brian-valeza/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brigitte Roka";
artist["link"] = "https://www.artofmtg.com/artist/brigitte-roka/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Brom";
artist["link"] = "https://www.artofmtg.com/artist/brom/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bryan Sola";
artist["link"] = "https://www.artofmtg.com/artist/bryan-sola/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Bud Cook";
artist["link"] = "https://www.artofmtg.com/artist/bud-cook/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Cabrol";
artist["link"] = "https://www.artofmtg.com/artist/cabrol/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Caio Monteiro";
artist["link"] = "https://www.artofmtg.com/artist/caio-monteiro/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Campbell White";
artist["link"] = "https://www.artofmtg.com/artist/campbell-white/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "CantWearHats";
artist["link"] = "https://www.artofmtg.com/artist/cantwearhats/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Card Name: Dauntless Avenger Converted Mana Cost: 3 Types: Creature — Human Soldier Card Text: Whenever Dauntless Avenger attacks";
artist["link"] = "https://www.artofmtg.com/artist/card-name-dauntless-avenger-converted-mana-cost-3-types-creature-human-soldier-card-text-whenever-dauntless-avenger-attacks/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Carl Critchlow";
artist["link"] = "https://www.artofmtg.com/artist/carl-critchlow/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Carl Frank";
artist["link"] = "https://www.artofmtg.com/artist/carl-frank/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Carly Mazur";
artist["link"] = "https://www.artofmtg.com/artist/carly-mazur/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Carmen Sinek";
artist["link"] = "https://www.artofmtg.com/artist/carmen-sinek/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Caroline Gariba";
artist["link"] = "https://www.artofmtg.com/artist/caroline-gariba/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chase Stone";
artist["link"] = "https://www.artofmtg.com/artist/chase-stone/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chippy";
artist["link"] = "https://www.artofmtg.com/artist/chippy/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chris Cold";
artist["link"] = "https://www.artofmtg.com/artist/chris-cold/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chris Ostrowski";
artist["link"] = "https://www.artofmtg.com/artist/chris-ostrowski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chris Ostrowski ‏";
artist["link"] = "https://www.artofmtg.com/artist/chris-ostrowski-%e2%80%8f/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chris Rahn";
artist["link"] = "https://www.artofmtg.com/artist/chris-rahn/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chris Rallis";
artist["link"] = "https://www.artofmtg.com/artist/chris-rallis/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chris Seaman";
artist["link"] = "https://www.artofmtg.com/artist/chris-seaman/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Christine Choi";
artist["link"] = "https://www.artofmtg.com/artist/christine-choi/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Christopher Burdett";
artist["link"] = "https://www.artofmtg.com/artist/christopher-burdett/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Christopher Lovell";
artist["link"] = "https://www.artofmtg.com/artist/christopher-lovell/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Christopher Moeller";
artist["link"] = "https://www.artofmtg.com/artist/christopher-moeller/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Christopher Rush";
artist["link"] = "https://www.artofmtg.com/artist/christopher-rush/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Chuck Lukacs";
artist["link"] = "https://www.artofmtg.com/artist/chuck-lukacs/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Cliff Childs";
artist["link"] = "https://www.artofmtg.com/artist/cliff-childs/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Clint Cearley";
artist["link"] = "https://www.artofmtg.com/artist/clint-cearley/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Colin Boyer";
artist["link"] = "https://www.artofmtg.com/artist/colin-boyer/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Collin Estrada";
artist["link"] = "https://www.artofmtg.com/artist/collin-estrada/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Craig J. Spearing";
artist["link"] = "https://www.artofmtg.com/artist/craig-j-spearing/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Cristi Balanescu";
artist["link"] = "https://www.artofmtg.com/artist/cristi-balanescu/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Cynthia Sheppard";
artist["link"] = "https://www.artofmtg.com/artist/cynthia-sheppard/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Cyril Van Der Haegen";
artist["link"] = "https://www.artofmtg.com/artist/cyril-van-der-haegen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "D. Alexander Gregory";
artist["link"] = "https://www.artofmtg.com/artist/d-alexander-gregory/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Daarken";
artist["link"] = "https://www.artofmtg.com/artist/daarken/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dallas Williams";
artist["link"] = "https://www.artofmtg.com/artist/dallas-williams/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dan Dos Santos";
artist["link"] = "https://www.artofmtg.com/artist/dan-dos-santos/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Daniel Ljunggren";
artist["link"] = "https://www.artofmtg.com/artist/daniel-ljunggren/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Daniel Warren Johnson";
artist["link"] = "https://www.artofmtg.com/artist/daniel-warren-johnson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Daniel Zrom";
artist["link"] = "https://www.artofmtg.com/artist/daniel-zrom/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dani Pendergast";
artist["link"] = "https://www.artofmtg.com/artist/dani-pendergast/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dan Mumford";
artist["link"] = "https://www.artofmtg.com/artist/dan-mumford/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Danny Miller";
artist["link"] = "https://www.artofmtg.com/artist/danny-miller/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dan Scott";
artist["link"] = "https://www.artofmtg.com/artist/dan-scott/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Darek Zabrocki";
artist["link"] = "https://www.artofmtg.com/artist/darek-zabrocki/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Daren Bader";
artist["link"] = "https://www.artofmtg.com/artist/daren-bader/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Daria Khlebnikova";
artist["link"] = "https://www.artofmtg.com/artist/daria-khlebnikova/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Darren Tan";
artist["link"] = "https://www.artofmtg.com/artist/darren-tan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dave Allsop";
artist["link"] = "https://www.artofmtg.com/artist/dave-allsop/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dave Dorman";
artist["link"] = "https://www.artofmtg.com/artist/dave-dorman/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dave Kendall";
artist["link"] = "https://www.artofmtg.com/artist/dave-kendall/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dave Rapoza";
artist["link"] = "https://www.artofmtg.com/artist/dave-rapoza/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "David Auden Nash";
artist["link"] = "https://www.artofmtg.com/artist/david-auden-nash/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "David Gaillet";
artist["link"] = "https://www.artofmtg.com/artist/david-gaillet/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "David Palumbo";
artist["link"] = "https://www.artofmtg.com/artist/david-palumbo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "David Rapoza";
artist["link"] = "https://www.artofmtg.com/artist/david-rapoza/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "David Sladek";
artist["link"] = "https://www.artofmtg.com/artist/david-sladek/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Denis Medri";
artist["link"] = "https://www.artofmtg.com/artist/denis-medri/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Denman Rooke";
artist["link"] = "https://www.artofmtg.com/artist/denman-rooke/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dermot Power";
artist["link"] = "https://www.artofmtg.com/artist/dermot-power/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Deruchenko Alexander";
artist["link"] = "https://www.artofmtg.com/artist/deruchenko-alexander/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dibujante Nocturno";
artist["link"] = "https://www.artofmtg.com/artist/dibujante-nocturno/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dimitar";
artist["link"] = "https://www.artofmtg.com/artist/dimitar/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dimitar Marinski";
artist["link"] = "https://www.artofmtg.com/artist/dimitar-marinski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "DiTerlizzi";
artist["link"] = "https://www.artofmtg.com/artist/diterlizzi/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dmitry Burmak";
artist["link"] = "https://www.artofmtg.com/artist/dmitry-burmak/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Dominik Mayer";
artist["link"] = "https://www.artofmtg.com/artist/dominik-mayer/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Donato Giancola";
artist["link"] = "https://www.artofmtg.com/artist/donato-giancola/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Don Hazeltine";
artist["link"] = "https://www.artofmtg.com/artist/don-hazeltine/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Douglas Shuler";
artist["link"] = "https://www.artofmtg.com/artist/douglas-shuler/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Drew Baker";
artist["link"] = "https://www.artofmtg.com/artist/drew-baker/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Drew Tucker";
artist["link"] = "https://www.artofmtg.com/artist/drew-tucker/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "DXTR";
artist["link"] = "https://www.artofmtg.com/artist/dxtr/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "DZO";
artist["link"] = "https://www.artofmtg.com/artist/dzo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "E. M. Gist";
artist["link"] = "https://www.artofmtg.com/artist/e-m-gist/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Eelis Kyttanen";
artist["link"] = "https://www.artofmtg.com/artist/eelis-kyttanen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ekaterina Burmak";
artist["link"] = "https://www.artofmtg.com/artist/ekaterina-burmak/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Eldritch Moon";
artist["link"] = "https://www.artofmtg.com/artist/eldritch-moon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Emma Rios";
artist["link"] = "https://www.artofmtg.com/artist/emma-rios/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Emrah Elmasli";
artist["link"] = "https://www.artofmtg.com/artist/emrah-elmasli/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Erica Williams";
artist["link"] = "https://www.artofmtg.com/artist/erica-williams/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Eric Deschamp";
artist["link"] = "https://www.artofmtg.com/artist/eric-deschamp/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Eric Deschamps";
artist["link"] = "https://www.artofmtg.com/artist/eric-deschamps/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Eric Fortune";
artist["link"] = "https://www.artofmtg.com/artist/eric-fortune/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Eric Wilkerson";
artist["link"] = "https://www.artofmtg.com/artist/eric-wilkerson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Evan Cagle";
artist["link"] = "https://www.artofmtg.com/artist/evan-cagle/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Even Amundsen";
artist["link"] = "https://www.artofmtg.com/artist/even-amundsen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Evyn Fong";
artist["link"] = "https://www.artofmtg.com/artist/evyn-fong/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Eytan Zana";
artist["link"] = "https://www.artofmtg.com/artist/eytan-zana/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Fajareka Setiawan";
artist["link"] = "https://www.artofmtg.com/artist/fajareka-setiawan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Filip Burburan";
artist["link"] = "https://www.artofmtg.com/artist/filip-burburan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Fiona Hsieh";
artist["link"] = "https://www.artofmtg.com/artist/fiona-hsieh/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Florian de Gesincourt";
artist["link"] = "https://www.artofmtg.com/artist/florian-de-gesincourt/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Forrest Imel";
artist["link"] = "https://www.artofmtg.com/artist/forrest-imel/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Francisco Miyara";
artist["link"] = "https://www.artofmtg.com/artist/francisco-miyara/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Franz Vohwinkel";
artist["link"] = "https://www.artofmtg.com/artist/franz-vohwinkel/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Fred Fields";
artist["link"] = "https://www.artofmtg.com/artist/fred-fields/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "G-host Lee";
artist["link"] = "https://www.artofmtg.com/artist/g-host-lee/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Gabor Szikszai";
artist["link"] = "https://www.artofmtg.com/artist/gabor-szikszai/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Godmachine";
artist["link"] = "https://www.artofmtg.com/artist/godmachine/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Goran Josic";
artist["link"] = "https://www.artofmtg.com/artist/goran-josic/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Grady Frederick";
artist["link"] = "https://www.artofmtg.com/artist/grady-frederick/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Greg Opalinski";
artist["link"] = "https://www.artofmtg.com/artist/greg-opalinski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Greg Staples";
artist["link"] = "https://www.artofmtg.com/artist/greg-staples/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Grzegorz Rutkowski";
artist["link"] = "https://www.artofmtg.com/artist/grzegorz-rutkowski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Hector Ortiz";
artist["link"] = "https://www.artofmtg.com/artist/hector-ortiz/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Heonhwa Choe";
artist["link"] = "https://www.artofmtg.com/artist/heonhwa-choe/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Hideaki Takamura";
artist["link"] = "https://www.artofmtg.com/artist/hideaki-takamura/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "hilip Straub";
artist["link"] = "https://www.artofmtg.com/artist/hilip-straub/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Hillary Wilson";
artist["link"] = "https://www.artofmtg.com/artist/hillary-wilson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Hiro Izawa";
artist["link"] = "https://www.artofmtg.com/artist/hiro-izawa/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Howard Lyon";
artist["link"] = "https://www.artofmtg.com/artist/howard-lyon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ian Miller";
artist["link"] = "https://www.artofmtg.com/artist/ian-miller/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Igor Kieryluk";
artist["link"] = "https://www.artofmtg.com/artist/igor-kieryluk/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ilse Gort";
artist["link"] = "https://www.artofmtg.com/artist/ilse-gort/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Inc.";
artist["link"] = "https://www.artofmtg.com/artist/inc/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Irina Nordsol";
artist["link"] = "https://www.artofmtg.com/artist/irina-nordsol/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Iris Compiet";
artist["link"] = "https://www.artofmtg.com/artist/iris-compiet/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Izzy";
artist["link"] = "https://www.artofmtg.com/artist/izzy/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "J.P. Targete";
artist["link"] = "https://www.artofmtg.com/artist/j-p-targete/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jack Wang";
artist["link"] = "https://www.artofmtg.com/artist/jack-wang/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jaime A. Zuverza";
artist["link"] = "https://www.artofmtg.com/artist/jaime-a-zuverza/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jaime Jones";
artist["link"] = "https://www.artofmtg.com/artist/jaime-jones/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jake Murray";
artist["link"] = "https://www.artofmtg.com/artist/jake-murray/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jakob Eirich";
artist["link"] = "https://www.artofmtg.com/artist/jakob-eirich/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jakub Kasper";
artist["link"] = "https://www.artofmtg.com/artist/jakub-kasper/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jakus Kasper";
artist["link"] = "https://www.artofmtg.com/artist/jakus-kasper/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "James Arnold";
artist["link"] = "https://www.artofmtg.com/artist/james-arnold/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "James Paick";
artist["link"] = "https://www.artofmtg.com/artist/james-paick/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "James Ryman";
artist["link"] = "https://www.artofmtg.com/artist/james-ryman/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "James Zapata";
artist["link"] = "https://www.artofmtg.com/artist/james-zapata/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jana Schirmer &amp; Johannes Voss";
artist["link"] = "https://www.artofmtg.com/artist/jana-schirmer-johannes-voss/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Janine Johnston";
artist["link"] = "https://www.artofmtg.com/artist/janine-johnston/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jarel Threat";
artist["link"] = "https://www.artofmtg.com/artist/jarel-threat/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jason A. Engle";
artist["link"] = "https://www.artofmtg.com/artist/jason-a-engle/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jason Chan";
artist["link"] = "https://www.artofmtg.com/artist/jason-chan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jason Felix";
artist["link"] = "https://www.artofmtg.com/artist/jason-felix/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jason Kang";
artist["link"] = "https://www.artofmtg.com/artist/jason-kang/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jason Rainville";
artist["link"] = "https://www.artofmtg.com/artist/jason-rainville/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jasper Sandner";
artist["link"] = "https://www.artofmtg.com/artist/jasper-sandner/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jean-Sébastien Rossbach";
artist["link"] = "https://www.artofmtg.com/artist/jean-sebastien-rossbach/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jedd Chevrier";
artist["link"] = "https://www.artofmtg.com/artist/jedd-chevrier/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jeff Easley";
artist["link"] = "https://www.artofmtg.com/artist/jeff-easley/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jeff Miracola";
artist["link"] = "https://www.artofmtg.com/artist/jeff-miracola/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jeffrey R. Busch";
artist["link"] = "https://www.artofmtg.com/artist/jeffrey-r-busch/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jeff Simpson";
artist["link"] = "https://www.artofmtg.com/artist/jeff-simpson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jehan Choo";
artist["link"] = "https://www.artofmtg.com/artist/jehan-choo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jen Bartel";
artist["link"] = "https://www.artofmtg.com/artist/jen-bartel/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jenn Ravenna";
artist["link"] = "https://www.artofmtg.com/artist/jenn-ravenna/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jeremy Jarvis";
artist["link"] = "https://www.artofmtg.com/artist/jeremy-jarvis/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jeremy Wilson";
artist["link"] = "https://www.artofmtg.com/artist/jeremy-wilson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jermaine Rogers";
artist["link"] = "https://www.artofmtg.com/artist/jermaine-rogers/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jesper Ejsing";
artist["link"] = "https://www.artofmtg.com/artist/jesper-ejsing/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jim Murray";
artist["link"] = "https://www.artofmtg.com/artist/jim-murray/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jim Nelson";
artist["link"] = "https://www.artofmtg.com/artist/jim-nelson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jim Pavelec";
artist["link"] = "https://www.artofmtg.com/artist/jim-pavelec/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jodie Muir";
artist["link"] = "https://www.artofmtg.com/artist/jodie-muir/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Joe Slucher";
artist["link"] = "https://www.artofmtg.com/artist/joe-slucher/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Johan Grenier";
artist["link"] = "https://www.artofmtg.com/artist/johan-grenier/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Johann Bodin";
artist["link"] = "https://www.artofmtg.com/artist/johann-bodin/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Johannes Voss";
artist["link"] = "https://www.artofmtg.com/artist/johannes-voss/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "John Avon";
artist["link"] = "https://www.artofmtg.com/artist/john-avon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "John Di Giovanni";
artist["link"] = "https://www.artofmtg.com/artist/john-di-giovanni/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "John Severin Brassell";
artist["link"] = "https://www.artofmtg.com/artist/john-severin-brassell/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "John Stanko";
artist["link"] = "https://www.artofmtg.com/artist/john-stanko/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "John Thacker";
artist["link"] = "https://www.artofmtg.com/artist/john-thacker/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jokubas Uogintas";
artist["link"] = "https://www.artofmtg.com/artist/jokubas-uogintas/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jonas De Ro";
artist["link"] = "https://www.artofmtg.com/artist/jonas-de-ro/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jonathan Kuo";
artist["link"] = "https://www.artofmtg.com/artist/jonathan-kuo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Joseph Meehan";
artist["link"] = "https://www.artofmtg.com/artist/joseph-meehan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Joseph Weston";
artist["link"] = "https://www.artofmtg.com/artist/joseph-weston/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Josh Hass";
artist["link"] = "https://www.artofmtg.com/artist/josh-hass/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Joshua Howard";
artist["link"] = "https://www.artofmtg.com/artist/joshua-howard/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Joshua Raphael";
artist["link"] = "https://www.artofmtg.com/artist/joshua-raphael/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Josu Hernaiz";
artist["link"] = "https://www.artofmtg.com/artist/josu-hernaiz/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Julie Dillon";
artist["link"] = "https://www.artofmtg.com/artist/julie-dillon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Julio Reyna";
artist["link"] = "https://www.artofmtg.com/artist/julio-reyna/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Jung Park";
artist["link"] = "https://www.artofmtg.com/artist/jung-park/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "JungShan";
artist["link"] = "https://www.artofmtg.com/artist/jungshan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Justine Cruz";
artist["link"] = "https://www.artofmtg.com/artist/justine-cruz/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Justine Jones";
artist["link"] = "https://www.artofmtg.com/artist/justine-jones/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Justine Mara Andersen";
artist["link"] = "https://www.artofmtg.com/artist/justine-mara-andersen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Justin Hernandez";
artist["link"] = "https://www.artofmtg.com/artist/justin-hernandez/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Justin Sweet";
artist["link"] = "https://www.artofmtg.com/artist/justin-sweet/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Justyna Gil";
artist["link"] = "https://www.artofmtg.com/artist/justyna-gil/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kari Christensen";
artist["link"] = "https://www.artofmtg.com/artist/kari-christensen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Karla Ortiz";
artist["link"] = "https://www.artofmtg.com/artist/karla-ortiz/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Karl Kopinski";
artist["link"] = "https://www.artofmtg.com/artist/karl-kopinski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kasia 'Kafis' Zielinska";
artist["link"] = "https://www.artofmtg.com/artist/kasia-kafis-zielinska/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kekai Kotaki";
artist["link"] = "https://www.artofmtg.com/artist/kekai-kotaki/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kev Walker";
artist["link"] = "https://www.artofmtg.com/artist/kev-walker/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Khurrum";
artist["link"] = "https://www.artofmtg.com/artist/khurrum/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kieran Yanner";
artist["link"] = "https://www.artofmtg.com/artist/kieran-yanner/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kimonas Theodossiou";
artist["link"] = "https://www.artofmtg.com/artist/kimonas-theodossiou/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kim Sokol";
artist["link"] = "https://www.artofmtg.com/artist/kim-sokol/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kirsten Zirngibl";
artist["link"] = "https://www.artofmtg.com/artist/kirsten-zirngibl/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kisung Koh";
artist["link"] = "https://www.artofmtg.com/artist/kisung-koh/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "KNIIO";
artist["link"] = "https://www.artofmtg.com/artist/kniio/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kotakan";
artist["link"] = "https://www.artofmtg.com/artist/kotakan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Koya Nakatsudo";
artist["link"] = "https://www.artofmtg.com/artist/koya-nakatsudo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Kristina Collantes";
artist["link"] = "https://www.artofmtg.com/artist/kristina-collantes/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lake Hurwitz";
artist["link"] = "https://www.artofmtg.com/artist/lake-hurwitz/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lars Grant-West";
artist["link"] = "https://www.artofmtg.com/artist/lars-grant-west/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lauren YS";
artist["link"] = "https://www.artofmtg.com/artist/lauren-ys/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Leanna Crossan";
artist["link"] = "https://www.artofmtg.com/artist/leanna-crossan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Leesha Hannigan";
artist["link"] = "https://www.artofmtg.com/artist/leesha-hannigan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lie Setiawan";
artist["link"] = "https://www.artofmtg.com/artist/lie-setiawan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Liiga Smilshkalne";
artist["link"] = "https://www.artofmtg.com/artist/liiga-smilshkalne/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lindsey Look";
artist["link"] = "https://www.artofmtg.com/artist/lindsey-look/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lius Lasahido";
artist["link"] = "https://www.artofmtg.com/artist/lius-lasahido/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Livia Prima";
artist["link"] = "https://www.artofmtg.com/artist/livia-prima/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lorenzo Lanfranconi";
artist["link"] = "https://www.artofmtg.com/artist/lorenzo-lanfranconi/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lorenzo Mastroianni";
artist["link"] = "https://www.artofmtg.com/artist/lorenzo-mastroianni/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lucas Graciano";
artist["link"] = "https://www.artofmtg.com/artist/lucas-graciano/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Lucas Staniec";
artist["link"] = "https://www.artofmtg.com/artist/lucas-staniec/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Maciej Kuciara";
artist["link"] = "https://www.artofmtg.com/artist/maciej-kuciara/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Magali Villeneuve";
artist["link"] = "https://www.artofmtg.com/artist/magali-villeneuve/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Maiko Aoji";
artist["link"] = "https://www.artofmtg.com/artist/maiko-aoji/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Manuel Castañón";
artist["link"] = "https://www.artofmtg.com/artist/manuel-castanon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Marco Nelor";
artist["link"] = "https://www.artofmtg.com/artist/marco-nelor/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Marc Simonetti";
artist["link"] = "https://www.artofmtg.com/artist/marc-simonetti/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Maria Abagnale";
artist["link"] = "https://www.artofmtg.com/artist/maria-abagnale/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Maria Poliakova";
artist["link"] = "https://www.artofmtg.com/artist/maria-poliakova/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Marie Magny";
artist["link"] = "https://www.artofmtg.com/artist/marie-magny/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mark Behm";
artist["link"] = "https://www.artofmtg.com/artist/mark-behm/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mark Poole";
artist["link"] = "https://www.artofmtg.com/artist/mark-poole/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mark Riddick";
artist["link"] = "https://www.artofmtg.com/artist/mark-riddick/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mark Tedin";
artist["link"] = "https://www.artofmtg.com/artist/mark-tedin/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mark Winters";
artist["link"] = "https://www.artofmtg.com/artist/mark-winters/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mark Zug";
artist["link"] = "https://www.artofmtg.com/artist/mark-zug/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Marta Nael";
artist["link"] = "https://www.artofmtg.com/artist/marta-nael/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Martina Fackova";
artist["link"] = "https://www.artofmtg.com/artist/martina-fackova/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Martina Pilcerova";
artist["link"] = "https://www.artofmtg.com/artist/martina-pilcerova/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mathias Kollros";
artist["link"] = "https://www.artofmtg.com/artist/mathias-kollros/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matt Cavotta";
artist["link"] = "https://www.artofmtg.com/artist/matt-cavotta/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matt Dixon";
artist["link"] = "https://www.artofmtg.com/artist/matt-dixon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matteo Bassini";
artist["link"] = "https://www.artofmtg.com/artist/matteo-bassini/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matt Gaser";
artist["link"] = "https://www.artofmtg.com/artist/matt-gaser/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matthew D. Wilson";
artist["link"] = "https://www.artofmtg.com/artist/matthew-d-wilson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matthew G. Lewis";
artist["link"] = "https://www.artofmtg.com/artist/matthew-g-lewis/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matthias Kollros";
artist["link"] = "https://www.artofmtg.com/artist/matthias-kollros/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Matt Stewart";
artist["link"] = "https://www.artofmtg.com/artist/matt-stewart/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Micah Epstein";
artist["link"] = "https://www.artofmtg.com/artist/micah-epstein/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Michael C. Hayes";
artist["link"] = "https://www.artofmtg.com/artist/michael-c-hayes/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Michael Komarck";
artist["link"] = "https://www.artofmtg.com/artist/michael-komarck/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Michael Walsh";
artist["link"] = "https://www.artofmtg.com/artist/michael-walsh/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Miguel Mercado";
artist["link"] = "https://www.artofmtg.com/artist/miguel-mercado/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mike Bierek";
artist["link"] = "https://www.artofmtg.com/artist/mike-bierek/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mike Burns";
artist["link"] = "https://www.artofmtg.com/artist/mike-burns/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mike Jordana";
artist["link"] = "https://www.artofmtg.com/artist/mike-jordana/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mike Sass";
artist["link"] = "https://www.artofmtg.com/artist/mike-sass/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mike Uziel";
artist["link"] = "https://www.artofmtg.com/artist/mike-uziel/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mila Pesic";
artist["link"] = "https://www.artofmtg.com/artist/mila-pesic/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Milivoj Ceran";
artist["link"] = "https://www.artofmtg.com/artist/milivoj-ceran/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Minttu Hynninen";
artist["link"] = "https://www.artofmtg.com/artist/minttu-hynninen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Min Yum";
artist["link"] = "https://www.artofmtg.com/artist/min-yum/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Miranda Meeks";
artist["link"] = "https://www.artofmtg.com/artist/miranda-meeks/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Mitchell Malloy";
artist["link"] = "https://www.artofmtg.com/artist/mitchell-malloy/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Morningtide";
artist["link"] = "https://www.artofmtg.com/artist/morningtide/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Muhammad Firdaus";
artist["link"] = "https://www.artofmtg.com/artist/muhammad-firdaus/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nagano";
artist["link"] = "https://www.artofmtg.com/artist/nagano/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Naomi Baker";
artist["link"] = "https://www.artofmtg.com/artist/naomi-baker/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nicholas Elias";
artist["link"] = "https://www.artofmtg.com/artist/nicholas-elias/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nicholas Gregory";
artist["link"] = "https://www.artofmtg.com/artist/nicholas-gregory/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nic Klein";
artist["link"] = "https://www.artofmtg.com/artist/nic-klein/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nick Percival";
artist["link"] = "https://www.artofmtg.com/artist/nick-percival/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nick Southam";
artist["link"] = "https://www.artofmtg.com/artist/nick-southam/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nico Delort";
artist["link"] = "https://www.artofmtg.com/artist/nico-delort/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nils Hamm";
artist["link"] = "https://www.artofmtg.com/artist/nils-hamm/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Noah Bradley";
artist["link"] = "https://www.artofmtg.com/artist/noah-bradley/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Nottsuo";
artist["link"] = "https://www.artofmtg.com/artist/nottsuo/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Olena Richards";
artist["link"] = "https://www.artofmtg.com/artist/olena-richards/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Olivier Bernard";
artist["link"] = "https://www.artofmtg.com/artist/olivier-bernard/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Omar Rayyan";
artist["link"] = "https://www.artofmtg.com/artist/omar-rayyan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Oriana Menendez";
artist["link"] = "https://www.artofmtg.com/artist/oriana-menendez/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ovidio Cartagena";
artist["link"] = "https://www.artofmtg.com/artist/ovidio-cartagena/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Paolo Parente";
artist["link"] = "https://www.artofmtg.com/artist/paolo-parente/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Paolo Puggioni";
artist["link"] = "https://www.artofmtg.com/artist/paolo-puggioni/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Pascal Blanchi";
artist["link"] = "https://www.artofmtg.com/artist/pascal-blanchi/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Paul Bonner";
artist["link"] = "https://www.artofmtg.com/artist/paul-bonner/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Pauline Voss";
artist["link"] = "https://www.artofmtg.com/artist/pauline-voss/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Paul Scott Canavan";
artist["link"] = "https://www.artofmtg.com/artist/paul-scott-canavan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Pedro Potier";
artist["link"] = "https://www.artofmtg.com/artist/pedro-potier/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Peter Mohrbacher";
artist["link"] = "https://www.artofmtg.com/artist/peter-mohrbacher/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Pete Venters";
artist["link"] = "https://www.artofmtg.com/artist/pete-venters/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Philip Straub";
artist["link"] = "https://www.artofmtg.com/artist/philip-straub/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Philip Straus";
artist["link"] = "https://www.artofmtg.com/artist/philip-straus/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Phill Simmer";
artist["link"] = "https://www.artofmtg.com/artist/phill-simmer/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "PINDURSKI";
artist["link"] = "https://www.artofmtg.com/artist/pindurski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Piotr Dura";
artist["link"] = "https://www.artofmtg.com/artist/piotr-dura/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Quinton Hoover";
artist["link"] = "https://www.artofmtg.com/artist/quinton-hoover/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ralph Horsley";
artist["link"] = "https://www.artofmtg.com/artist/ralph-horsley/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Randy Gallegos";
artist["link"] = "https://www.artofmtg.com/artist/randy-gallegos/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Randy Vargas";
artist["link"] = "https://www.artofmtg.com/artist/randy-vargas/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Raoul Vitale";
artist["link"] = "https://www.artofmtg.com/artist/raoul-vitale/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Raymond Swanland";
artist["link"] = "https://www.artofmtg.com/artist/raymond-swanland/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Rebecca Guay";
artist["link"] = "https://www.artofmtg.com/artist/rebecca-guay/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Rian Gonzalez";
artist["link"] = "https://www.artofmtg.com/artist/rian-gonzalez/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Richard Kane Ferguson";
artist["link"] = "https://www.artofmtg.com/artist/richard-kane-ferguson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Richard Luong";
artist["link"] = "https://www.artofmtg.com/artist/richard-luong/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Richard Wright";
artist["link"] = "https://www.artofmtg.com/artist/richard-wright/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Rien";
artist["link"] = "https://www.artofmtg.com/artist/rien/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "rk post";
artist["link"] = "https://www.artofmtg.com/artist/rk-post/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "RoarkMeow";
artist["link"] = "https://www.artofmtg.com/artist/roarkmeow/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Rob Alexander";
artist["link"] = "https://www.artofmtg.com/artist/rob-alexander/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Robbie Trevino";
artist["link"] = "https://www.artofmtg.com/artist/robbie-trevino/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Romana Kendelic";
artist["link"] = "https://www.artofmtg.com/artist/romana-kendelic/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Roman Kuteynikov";
artist["link"] = "https://www.artofmtg.com/artist/roman-kuteynikov/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ron Spears";
artist["link"] = "https://www.artofmtg.com/artist/ron-spears/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ron Spencer";
artist["link"] = "https://www.artofmtg.com/artist/ron-spencer/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Rovina Cai";
artist["link"] = "https://www.artofmtg.com/artist/rovina-cai/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Rudy Siswanto";
artist["link"] = "https://www.artofmtg.com/artist/rudy-siswanto/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Russ Nicholson";
artist["link"] = "https://www.artofmtg.com/artist/russ-nicholson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ryan Alexander Lee";
artist["link"] = "https://www.artofmtg.com/artist/ryan-alexander-lee/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ryan Barger";
artist["link"] = "https://www.artofmtg.com/artist/ryan-barger/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ryan Pancoast";
artist["link"] = "https://www.artofmtg.com/artist/ryan-pancoast/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Ryan Yee";
artist["link"] = "https://www.artofmtg.com/artist/ryan-yee/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "rzegorz Rutkowski";
artist["link"] = "https://www.artofmtg.com/artist/rzegorz-rutkowski/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sam Burley";
artist["link"] = "https://www.artofmtg.com/artist/sam-burley/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sam Guay";
artist["link"] = "https://www.artofmtg.com/artist/sam-guay/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sam Rowan";
artist["link"] = "https://www.artofmtg.com/artist/sam-rowan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sam White";
artist["link"] = "https://www.artofmtg.com/artist/sam-white/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "sandara";
artist["link"] = "https://www.artofmtg.com/artist/sandara/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sarah Finnigan";
artist["link"] = "https://www.artofmtg.com/artist/sarah-finnigan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sara Winters";
artist["link"] = "https://www.artofmtg.com/artist/sara-winters/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Scott Chou";
artist["link"] = "https://www.artofmtg.com/artist/scott-chou/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Scott M. Fischer";
artist["link"] = "https://www.artofmtg.com/artist/scott-m-fischer/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Scott Murphy";
artist["link"] = "https://www.artofmtg.com/artist/scott-murphy/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sean Murray";
artist["link"] = "https://www.artofmtg.com/artist/sean-murray/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sean Sevestre";
artist["link"] = "https://www.artofmtg.com/artist/sean-sevestre/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Seb McKinnon";
artist["link"] = "https://www.artofmtg.com/artist/seb-mckinnon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Shelly Wan";
artist["link"] = "https://www.artofmtg.com/artist/shelly-wan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Shishizaru";
artist["link"] = "https://www.artofmtg.com/artist/shishizaru/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Shreya Shetty";
artist["link"] = "https://www.artofmtg.com/artist/shreya-shetty/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sidharth Chaturvedi";
artist["link"] = "https://www.artofmtg.com/artist/sidharth-chaturvedi/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Simon Dominic";
artist["link"] = "https://www.artofmtg.com/artist/simon-dominic/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Slawomir Maniak";
artist["link"] = "https://www.artofmtg.com/artist/slawomir-maniak/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Stanton Feng";
artist["link"] = "https://www.artofmtg.com/artist/stanton-feng/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Stephan Martiniere";
artist["link"] = "https://www.artofmtg.com/artist/stephan-martiniere/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Steve Argyle";
artist["link"] = "https://www.artofmtg.com/artist/steve-argyle/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Steve Ellis";
artist["link"] = "https://www.artofmtg.com/artist/steve-ellis/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Steven Belledin";
artist["link"] = "https://www.artofmtg.com/artist/steven-belledin/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Steven Russel Black";
artist["link"] = "https://www.artofmtg.com/artist/steven-russel-black/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Steve Prescott";
artist["link"] = "https://www.artofmtg.com/artist/steve-prescott/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sumie Okazu";
artist["link"] = "https://www.artofmtg.com/artist/sumie-okazu/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Sung Choi";
artist["link"] = "https://www.artofmtg.com/artist/sung-choi/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Suzanne Helmigh";
artist["link"] = "https://www.artofmtg.com/artist/suzanne-helmigh/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Svetlin Velinov";
artist["link"] = "https://www.artofmtg.com/artist/svetlin-velinov/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Terese Nielsen";
artist["link"] = "https://www.artofmtg.com/artist/terese-nielsen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "TheStrangeEli";
artist["link"] = "https://www.artofmtg.com/artist/thestrangeeli/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Thomas M. Baxa";
artist["link"] = "https://www.artofmtg.com/artist/thomas-m-baxa/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Thomas Zenteno";
artist["link"] = "https://www.artofmtg.com/artist/thomas-zenteno/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tianhua X";
artist["link"] = "https://www.artofmtg.com/artist/tianhua-x/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Titus Lunter";
artist["link"] = "https://www.artofmtg.com/artist/titus-lunter/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Todd Lockwood";
artist["link"] = "https://www.artofmtg.com/artist/todd-lockwood/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tomasz Jedruszek";
artist["link"] = "https://www.artofmtg.com/artist/tomasz-jedruszek/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tommy Arnold";
artist["link"] = "https://www.artofmtg.com/artist/tommy-arnold/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tony Foti";
artist["link"] = "https://www.artofmtg.com/artist/tony-foti/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tran Nguyen";
artist["link"] = "https://www.artofmtg.com/artist/tran-nguyen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tsutomu Kawade";
artist["link"] = "https://www.artofmtg.com/artist/tsutomu-kawade/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tuan Duong Chu";
artist["link"] = "https://www.artofmtg.com/artist/tuan-duong-chu/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tyle Crook";
artist["link"] = "https://www.artofmtg.com/artist/tyle-crook/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tyler Jacobson";
artist["link"] = "https://www.artofmtg.com/artist/tyler-jacobson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tyler Smith";
artist["link"] = "https://www.artofmtg.com/artist/tyler-smith/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Tyler Walpole";
artist["link"] = "https://www.artofmtg.com/artist/tyler-walpole/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Udon";
artist["link"] = "https://www.artofmtg.com/artist/udon/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Valera Lutfullina";
artist["link"] = "https://www.artofmtg.com/artist/valera-lutfullina/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Vance Kovacs";
artist["link"] = "https://www.artofmtg.com/artist/vance-kovacs/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Victor Adame Minguez";
artist["link"] = "https://www.artofmtg.com/artist/victor-adame-minguez/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Viko Menezes";
artist["link"] = "https://www.artofmtg.com/artist/viko-menezes/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Viktor Titov";
artist["link"] = "https://www.artofmtg.com/artist/viktor-titov/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Vincent Proce";
artist["link"] = "https://www.artofmtg.com/artist/vincent-proce/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Vincent Procee";
artist["link"] = "https://www.artofmtg.com/artist/vincent-procee/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Vi Szendrey (Cashile)";
artist["link"] = "https://www.artofmtg.com/artist/vi-szendrey-cashile/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Volkan Baga";
artist["link"] = "https://www.artofmtg.com/artist/volkan-baga/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Véronique Meignaud";
artist["link"] = "https://www.artofmtg.com/artist/veronique-meignaud/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Warren Mahy";
artist["link"] = "https://www.artofmtg.com/artist/warren-mahy/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Wayne England";
artist["link"] = "https://www.artofmtg.com/artist/wayne-england/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Wayne Reynolds";
artist["link"] = "https://www.artofmtg.com/artist/wayne-reynolds/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Wesley Burt";
artist["link"] = "https://www.artofmtg.com/artist/wesley-burt/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Whit Brachna";
artist["link"] = "https://www.artofmtg.com/artist/whit-brachna/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "William Wu";
artist["link"] = "https://www.artofmtg.com/artist/william-wu/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Willian Murai";
artist["link"] = "https://www.artofmtg.com/artist/willian-murai/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Winona Nelson";
artist["link"] = "https://www.artofmtg.com/artist/winona-nelson/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Wisnu Tan";
artist["link"] = "https://www.artofmtg.com/artist/wisnu-tan/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Wizard of Barge";
artist["link"] = "https://www.artofmtg.com/artist/wizard-of-barge/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "WolfSkullJack";
artist["link"] = "https://www.artofmtg.com/artist/wolfskulljack/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Wylie Beckert";
artist["link"] = "https://www.artofmtg.com/artist/wylie-beckert/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Yeong-Hao Han";
artist["link"] = "https://www.artofmtg.com/artist/yeong-hao-han/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Yigit Koroglu";
artist["link"] = "https://www.artofmtg.com/artist/yigit-koroglu/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Yohann Schepacz";
artist["link"] = "https://www.artofmtg.com/artist/yohann-schepacz/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Yongjae Choi";
artist["link"] = "https://www.artofmtg.com/artist/yongjae-choi/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "YW Tang";
artist["link"] = "https://www.artofmtg.com/artist/yw-tang/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Zack Stella";
artist["link"] = "https://www.artofmtg.com/artist/zack-stella/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Zara Alfonso";
artist["link"] = "https://www.artofmtg.com/artist/zara-alfonso/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Zezhou Chen";
artist["link"] = "https://www.artofmtg.com/artist/zezhou-chen/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Zoltan Boros";
artist["link"] = "https://www.artofmtg.com/artist/zoltan-boros/";
artist_list.push(artist);
artist = Object.create(artist_template);
artist["name"] = "Zoltan Boros &amp; Gabor Szikszai";
artist["link"] = "https://www.artofmtg.com/artist/zoltan-boros-gabor-szikszai/";
artist_list.push(artist);

return artist_list
// console.log(artist_list);
}